question_data = {"response_code": 0,
                 "results": [
                     {"category": "Geography",
                      "type": "boolean",
                      "difficulty": "easy",
                      "question": "San Marino is the only country completely surrounded by another country.",
                      "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"category": "Art", "type": "boolean", "difficulty": "medium",
                      "question": "Vincent van Gogh cut off one of his ears.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Science & Nature", "type": "boolean",
                      "difficulty": "medium",
                      "question": "Scientists accidentally killed the once known world&#039;s oldest living creature, a mollusc, known to be aged as 507 years old.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Entertainment: Video Games", "type": "boolean",
                      "difficulty": "medium",
                      "question": "TF2: The Medic will be credited for an assist if he heals a Spy that successfully saps a building.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Geography", "type": "boolean", "difficulty": "medium",
                      "question": "The Sonoran Desert is located in eastern Africa.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "Entertainment: Video Games", "type": "boolean",
                      "difficulty": "easy",
                      "question": "&quot;Metal Gear Solid 3: Snake Eater&quot; was released in 2004.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Entertainment: Video Games", "type": "boolean",
                      "difficulty": "easy",
                      "question": "Several characters in &quot;Super Mario 64&quot; blink their eyes, including Mario himself.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Politics", "type": "boolean", "difficulty": "easy",
                      "question": "Former president Theodore Roosevelt (1900-1908)  ran for another term under the Progressive Party in 1912.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean",
                      "difficulty": "easy",
                      "question": "Slovakia is a member of European Union-",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Entertainment: Video Games", "type": "boolean",
                      "difficulty": "easy",
                      "question": "Each piece in Tetris is called a tetris.",
                      "correct_answer": "False", "incorrect_answers": ["True"]}]}
